//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.CreditcardPaymentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Payments")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreditcardPaymentService.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetData", ReplyAction="http://tempuri.org/IPaymentService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetData", ReplyAction="http://tempuri.org/IPaymentService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IPaymentService/GetDataUsingDataContractResponse")]
        WCFClient.CreditcardPaymentService.CompositeType GetDataUsingDataContract(WCFClient.CreditcardPaymentService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IPaymentService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WCFClient.CreditcardPaymentService.CompositeType> GetDataUsingDataContractAsync(WCFClient.CreditcardPaymentService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/WhatsYourId", ReplyAction="http://tempuri.org/IPaymentService/WhatsYourIdResponse")]
        string WhatsYourId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/WhatsYourId", ReplyAction="http://tempuri.org/IPaymentService/WhatsYourIdResponse")]
        System.Threading.Tasks.Task<string> WhatsYourIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/IsCardNumberValid", ReplyAction="http://tempuri.org/IPaymentService/IsCardNumberValidResponse")]
        bool IsCardNumberValid(string cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/IsCardNumberValid", ReplyAction="http://tempuri.org/IPaymentService/IsCardNumberValidResponse")]
        System.Threading.Tasks.Task<bool> IsCardNumberValidAsync(string cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/IsValidPaymentAmount", ReplyAction="http://tempuri.org/IPaymentService/IsValidPaymentAmountResponse")]
        bool IsValidPaymentAmount(long amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/IsValidPaymentAmount", ReplyAction="http://tempuri.org/IPaymentService/IsValidPaymentAmountResponse")]
        System.Threading.Tasks.Task<bool> IsValidPaymentAmountAsync(long amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/CanMakePaymentWithCard", ReplyAction="http://tempuri.org/IPaymentService/CanMakePaymentWithCardResponse")]
        bool CanMakePaymentWithCard(string cardNumber, int expiryMonth, int expiryYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/CanMakePaymentWithCard", ReplyAction="http://tempuri.org/IPaymentService/CanMakePaymentWithCardResponse")]
        System.Threading.Tasks.Task<bool> CanMakePaymentWithCardAsync(string cardNumber, int expiryMonth, int expiryYear);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : WCFClient.CreditcardPaymentService.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<WCFClient.CreditcardPaymentService.IPaymentService>, WCFClient.CreditcardPaymentService.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WCFClient.CreditcardPaymentService.CompositeType GetDataUsingDataContract(WCFClient.CreditcardPaymentService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WCFClient.CreditcardPaymentService.CompositeType> GetDataUsingDataContractAsync(WCFClient.CreditcardPaymentService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string WhatsYourId() {
            return base.Channel.WhatsYourId();
        }
        
        public System.Threading.Tasks.Task<string> WhatsYourIdAsync() {
            return base.Channel.WhatsYourIdAsync();
        }
        
        public bool IsCardNumberValid(string cardNumber) {
            return base.Channel.IsCardNumberValid(cardNumber);
        }
        
        public System.Threading.Tasks.Task<bool> IsCardNumberValidAsync(string cardNumber) {
            return base.Channel.IsCardNumberValidAsync(cardNumber);
        }
        
        public bool IsValidPaymentAmount(long amount) {
            return base.Channel.IsValidPaymentAmount(amount);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidPaymentAmountAsync(long amount) {
            return base.Channel.IsValidPaymentAmountAsync(amount);
        }
        
        public bool CanMakePaymentWithCard(string cardNumber, int expiryMonth, int expiryYear) {
            return base.Channel.CanMakePaymentWithCard(cardNumber, expiryMonth, expiryYear);
        }
        
        public System.Threading.Tasks.Task<bool> CanMakePaymentWithCardAsync(string cardNumber, int expiryMonth, int expiryYear) {
            return base.Channel.CanMakePaymentWithCardAsync(cardNumber, expiryMonth, expiryYear);
        }
    }
}
